x-api: &api
  image: ghcr.io/toto9in/crab-antiagiota-performance:latest
  pull_policy: always
  platform: linux/amd64
  volumes:
    - sockets:/tmp/sockets
  deploy:
    resources:
      limits:
        cpus: "0.45"
        memory: 150M

services:
  lb:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/tmp/sockets
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 30M

  api1:
    <<: *api
    environment:
      SOCKET_PATH: /tmp/sockets/api1.sock

  api2:
    <<: *api
    environment:
      SOCKET_PATH: /tmp/sockets/api2.sock

volumes:
  sockets:
