services:
  lb:
    image: nginx:1.27-alpine
    platform: linux/amd64
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp/sockets
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 30M

  api1:
    image: ghcr.io/toto9in/crab-antiagiota-performance:latest
    pull_policy: always
    platform: linux/amd64
    environment:
      SOCKET_PATH: /tmp/sockets/api1.sock
    volumes:
      - sockets:/tmp/sockets
    deploy:
      resources:
        limits:
          cpus: "0.400"
          memory: 110M

  api2:
    image: ghcr.io/toto9in/crab-antiagiota-performance:latest
    pull_policy: always
    platform: linux/amd64
    environment:
      SOCKET_PATH: /tmp/sockets/api2.sock
    volumes:
      - sockets:/tmp/sockets
    deploy:
      resources:
        limits:
          cpus: "0.400"
          memory: 110M

volumes:
  sockets:
